configfile: "config/config.yaml"

# --- O NOVO RADAR ---
REFERENCES = glob_wildcards("data/raw/reference/{ref}/{ref_file}.fasta").ref
OUTGROUPS = glob_wildcards("data/raw/outgroup/{outgroup}/{outgroup_file}_1.fastq").outgroup
FOCALS = glob_wildcards("data/raw/focal/{focal}/{focal_file}_1.fastq").focal

GENOTYPERS = config["genotypers"]

# --- REGRA ALVO (12 ITERAÇÕES POR FOCAL) ---
rule all:
    input:
        expand("results/vcf_filtered/{focal}-{outgroup}-{reference}-{genotyper}.filtered.vcf",
               focal=FOCALS, outgroup=OUTGROUPS, reference=REFERENCES, genotyper=GENOTYPERS),
        "results/qc/multiqc_report.html",
        expand("results/qc/vcf_stats/{focal}-{outgroup}-{reference}-{genotyper}.vchk",
               focal=FOCALS, outgroup=OUTGROUPS, reference=REFERENCES, genotyper=GENOTYPERS),
        expand("results/pca/{focal}-{outgroup}-{reference}-{genotyper}.eigenvec",
               focal=FOCALS, outgroup=OUTGROUPS, reference=REFERENCES, genotyper=GENOTYPERS),
        expand("results/qc/pca_plots/{focal}-{outgroup}-{reference}-{genotyper}_pca.pdf",
               focal=FOCALS, outgroup=OUTGROUPS, reference=REFERENCES, genotyper=GENOTYPERS)

# --- INDEXAÇÕES DA REFERÊNCIA ---
rule indexar_bwa:
    input: "data/raw/reference/{reference}/{reference}.fasta"
    output:
        bwt="data/raw/reference/{reference}/{reference}.fasta.bwt",
        pac="data/raw/reference/{reference}/{reference}.fasta.pac",
        ann="data/raw/reference/{reference}/{reference}.fasta.ann",
        amb="data/raw/reference/{reference}/{reference}.fasta.amb",
        sa="data/raw/reference/{reference}/{reference}.fasta.sa"
    shell: "docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) staphb/bwa:0.7.17 bwa index {input}"

rule indexar_samtools_fai:
    input: "data/raw/reference/{reference}/{reference}.fasta"
    output: "data/raw/reference/{reference}/{reference}.fasta.fai"
    shell: "docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) staphb/samtools:1.17 samtools faidx {input}"

rule criar_dicionario_gatk:
    input: "data/raw/reference/{reference}/{reference}.fasta"
    output: "data/raw/reference/{reference}/{reference}.dict"
    shell: "docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) broadinstitute/gatk:4.4.0.0 gatk CreateSequenceDictionary -R {input} -O {output}"

# --- MAPEAMENTOS INDEPENDENTES ---
rule mapeamento_focal:
    input:
        fasta="data/raw/reference/{reference}/{reference}.fasta",
        bwt="data/raw/reference/{reference}/{reference}.fasta.bwt",
        r1="data/raw/focal/{focal}/{focal}_1.fastq",
        r2="data/raw/focal/{focal}/{focal}_2.fastq"
    output:
        bam="results/mapping/focal/{reference}-{focal}.sorted.bam"
    shell:
        """
        docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) staphb/bwa:0.7.17 \
        bwa mem -R "@RG\\tID:{wildcards.focal}\\tSM:{wildcards.focal}\\tPL:ILLUMINA" {input.fasta} {input.r1} {input.r2} | \
        docker run -i --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) staphb/samtools:1.17 \
        samtools sort -o {output.bam} -
        """

rule mapeamento_outgroup:
    input:
        fasta="data/raw/reference/{reference}/{reference}.fasta",
        bwt="data/raw/reference/{reference}/{reference}.fasta.bwt",
        r1="data/raw/outgroup/{outgroup}/{outgroup}_1.fastq",
        r2="data/raw/outgroup/{outgroup}/{outgroup}_2.fastq"
    output:
        bam="results/mapping/outgroup/{reference}-{outgroup}.sorted.bam"
    shell:
        """
        docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) staphb/bwa:0.7.17 \
        bwa mem -R "@RG\\tID:{wildcards.outgroup}\\tSM:{wildcards.outgroup}\\tPL:ILLUMINA" {input.fasta} {input.r1} {input.r2} | \
        docker run -i --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) staphb/samtools:1.17 \
        samtools sort -o {output.bam} -
        """

# --- INDEXAÇÕES DOS BAMS ---
rule indexar_bam_focal:
    input: "results/mapping/focal/{reference}-{focal}.sorted.bam"
    output: "results/mapping/focal/{reference}-{focal}.sorted.bam.bai"
    shell: "docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) staphb/samtools:1.17 samtools index {input}"

rule indexar_bam_outgroup:
    input: "results/mapping/outgroup/{reference}-{outgroup}.sorted.bam"
    output: "results/mapping/outgroup/{reference}-{outgroup}.sorted.bam.bai"
    shell: "docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) staphb/samtools:1.17 samtools index {input}"

# --- GENOTIPAGEM CONJUNTA (JOINT CALLING) ---
rule freebayes:
    input:
        fasta="data/raw/reference/{reference}/{reference}.fasta",
        bam_foc="results/mapping/focal/{reference}-{focal}.sorted.bam",
        bai_foc="results/mapping/focal/{reference}-{focal}.sorted.bam.bai",
        bam_out="results/mapping/outgroup/{reference}-{outgroup}.sorted.bam",
        bai_out="results/mapping/outgroup/{reference}-{outgroup}.sorted.bam.bai"
    output:
        vcf="results/vcf/{focal}-{outgroup}-{reference}-freebayes.vcf"
    shell:
        """
        docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) staphb/freebayes:1.3.6 \
        freebayes -f {input.fasta} {input.bam_foc} {input.bam_out} > {output.vcf}
        """

rule gatk_haplotype_caller:
    input:
        fasta="data/raw/reference/{reference}/{reference}.fasta",
        fai="data/raw/reference/{reference}/{reference}.fasta.fai",
        dict="data/raw/reference/{reference}/{reference}.dict",
        bam_foc="results/mapping/focal/{reference}-{focal}.sorted.bam",
        bai_foc="results/mapping/focal/{reference}-{focal}.sorted.bam.bai",
        bam_out="results/mapping/outgroup/{reference}-{outgroup}.sorted.bam",
        bai_out="results/mapping/outgroup/{reference}-{outgroup}.sorted.bam.bai"
    output:
        vcf="results/vcf/{focal}-{outgroup}-{reference}-gatk.vcf"
    shell:
        """
        docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) broadinstitute/gatk:4.4.0.0 \
        gatk HaplotypeCaller -R {input.fasta} -I {input.bam_foc} -I {input.bam_out} -O {output.vcf}
        """
# --- FILTRAGEM DE VARIANTES (HARD FILTERING) ---
rule filtragem_vcf:
    input:
        vcf="results/vcf/{focal}-{outgroup}-{reference}-{genotyper}.vcf"
    output:
        vcf_filt="results/vcf_filtered/{focal}-{outgroup}-{reference}-{genotyper}.filtered.vcf"
    shell:
        """
        docker run --rm -u $(id -u):$(id -g) -v "$(pwd)":"$(pwd)" -w "$(pwd)" staphb/bcftools:1.17 \
        bcftools filter -i 'QUAL>30' {input.vcf} > {output.vcf_filt}
        """

# --- CONTROLE DE QUALIDADE (QC) ---
rule samtools_stats_focal:
    input:
        bam="results/mapping/focal/{reference}-{focal}.sorted.bam"
    output:
        stats="results/qc/stats/focal/{reference}-{focal}.stats"
    shell:
        """
        docker run --rm -u $(id -u):$(id -g) -v "$(pwd)":"$(pwd)" -w "$(pwd)" staphb/samtools:1.17 \
        samtools stats {input.bam} > {output.stats}
        """

rule samtools_stats_outgroup:
    input:
        bam="results/mapping/outgroup/{reference}-{outgroup}.sorted.bam"
    output:
        stats="results/qc/stats/outgroup/{reference}-{outgroup}.stats"
    shell:
        """
        docker run --rm -u $(id -u):$(id -g) -v "$(pwd)":"$(pwd)" -w "$(pwd)" staphb/samtools:1.17 \
        samtools stats {input.bam} > {output.stats}
        """

rule multiqc:
    input:
        stats_foc=expand("results/qc/stats/focal/{reference}-{focal}.stats", reference=REFERENCES, focal=FOCALS),
        stats_out=expand("results/qc/stats/outgroup/{reference}-{outgroup}.stats", reference=REFERENCES, outgroup=OUTGROUPS)
    output:
        html="results/qc/multiqc_report.html"
    shell:
        """
        docker run --rm -u $(id -u):$(id -g) -v "$(pwd)":"$(pwd)" -w "$(pwd)" staphb/multiqc:1.14 \
        multiqc results/qc/stats/ -o results/qc/
        """
# --- ESTATÍSTICAS E GRÁFICOS DO VCF (TIPO FIGURE S1 E S2 DO ARTIGO) ---
rule vcf_stats:
    input:
        vcf="results/vcf_filtered/{focal}-{outgroup}-{reference}-{genotyper}.filtered.vcf"
    output:
        stats="results/qc/vcf_stats/{focal}-{outgroup}-{reference}-{genotyper}.vchk",
        plot_dir=directory("results/qc/vcf_stats/plots_{focal}_{outgroup}_{reference}_{genotyper}")
    shell:
        """
        # Extrai os dados matemáticos do VCF
        docker run --rm -u $(id -u):$(id -g) -v "$(pwd)":"$(pwd)" -w "$(pwd)" staphb/bcftools:1.17 \
        bcftools stats {input.vcf} > {output.stats}
        
        # Gera os gráficos automáticos em PDF usando o plot-vcfstats
        docker run --rm -u $(id -u):$(id -g) -v "$(pwd)":"$(pwd)" -w "$(pwd)" staphb/bcftools:1.17 \
        plot-vcfstats -p {output.plot_dir} {output.stats}
        """

# --- PREPARAÇÃO PARA O PCA (TIPO FIGURE 4 DO ARTIGO) ---
rule pca_plink:
    input:
        vcf="results/vcf_filtered/{focal}-{outgroup}-{reference}-{genotyper}.filtered.vcf"
    output:
        eigenval="results/pca/{focal}-{outgroup}-{reference}-{genotyper}.eigenval",
        eigenvec="results/pca/{focal}-{outgroup}-{reference}-{genotyper}.eigenvec"
    params:
        out_prefix="results/pca/{focal}-{outgroup}-{reference}-{genotyper}"
    shell:
        """
        # PLINK vai ler o VCF e calcular as coordenadas X e Y de cada planta para o PCA
        docker run --rm -u $(id -u):$(id -g) -v "$(pwd)":"$(pwd)" -w "$(pwd)" staphb/plink:1.90b6.21 \
        plink --vcf-half-call m --vcf {input.vcf} --double-id --allow-extra-chr --set-missing-var-ids @:# \
        --pca --out {params.out_prefix}
        """
rule plot_pca:
    input:
        eigenvec="results/pca/{focal}-{outgroup}-{reference}-{genotyper}.eigenvec"
    output:
        pdf="results/qc/pca_plots/{focal}-{outgroup}-{reference}-{genotyper}_pca.pdf"
    shell:
        """
        docker run --rm -u $(id -u):$(id -g) -v "$(pwd)":"$(pwd)" -w "$(pwd)" rocker/tidyverse:4.3.1 \
        Rscript scripts/plot_pca.R {input.eigenvec} {output.pdf}
        """
